{
 "title": "Jenkins Build Status",
 "description": "Provides build health stats for each repo in an org",
 "tags": [
  "devops",
  "jenkins",
  "dev",
  "in-progress"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "bussiness", "label": "Folder", "query": "show measurements" },
   {
    "name": "job",
    "label": "Job",
    "query": "select project_name from $bussiness"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "Passed",
     "measurement": "job",
     "query": "SELECT count(\"build_id\") FROM \"$bussiness\" WHERE (\"project_name\" =~ /^$job$/ AND  \"build_result\" = 1) ",
     "select": [
      [
       { "params": [ "jobtime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "CompletedSuccess" }
     ]
    },
    {
     "alias": "Failed",
     "measurement": "job",
     "query": "SELECT count(\"build_id\") FROM \"$bussiness\" WHERE (\"project_name\" =~ /^$job$/ AND  \"build_result\" = 0) ",
     "select": [
      [
       { "params": [ "jobtime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "CompletedError" }
     ]
    }
   ]
  },
  {
   "title": "总构建次数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "measurement": "job",
     "query": "SELECT count(\"build_id\") FROM \"$bussiness\" WHERE (\"project_name\" =~ /^$job$/ )",
     "select": [
      [
       { "params": [ "jobtime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "平均构建时间",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "job",
     "query": "SELECT \"build_time\"  / 1000 FROM \"$bussiness\" WHERE (\"project_name\" =~ /^$job$/)",
     "select": [
      [
       { "params": [ "jobtime" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "单元测试",
   "type": "bargauge",
   "description": "最后一次单元测试结果",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "alias": "Passed",
     "measurement": "tests",
     "query": "SELECT last(\"tests_passed\")  / (tests_passed + tests_skipped + tests_failed) FROM \"$bussiness\" WHERE (\"project_name\" =~ /^$job$/)",
     "select": [
      [
       { "params": [ "passed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / (passed + skipped + failed)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    },
    {
     "alias": "Skipped",
     "measurement": "tests",
     "query": "SELECT last(\"tests_skipped\")  / (tests_passed + tests_skipped + tests_failed) FROM \"$bussiness\" WHERE (\"project_name\" =~ /^$job$/)",
     "select": [
      [
       { "params": [ "skipped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / (passed + skipped + failed)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    },
    {
     "alias": "Failed",
     "measurement": "tests",
     "query": "SELECT last(\"tests_failed\")  / (tests_passed + tests_skipped + tests_failed) FROM \"$bussiness\" WHERE (\"project_name\" =~ /^$job$/)",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / (passed + skipped + failed)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "最后一次构建状态",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "job",
     "query": "SELECT last(\"build_result\") FROM \"$bussiness\" WHERE (\"project_name\" =~ /^$job$/)",
     "select": [
      [
       { "params": [ "passed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Duration Trend",
   "type": "btplc-trend-box-panel",
   "description": "This graph shows the percentage change of build duration between the latest run and the first one. The graph will be green if value <= 0; yellow if 0 < value <= 25; and red if value > 25",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 4 },
   "format": "ms",
   "targets": [
    {
     "measurement": "job",
     "query": "SELECT \"build_time\" FROM \"$bussiness\" WHERE (\"project_name\" =~ /^$job$/ )",
     "select": [
      [
       { "params": [ "jobtime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "测试结果",
   "type": "bargauge",
   "description": "最后一个测试覆盖率结果",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 4 },
   "targets": [
    {
     "alias": "Classes",
     "measurement": "coverage",
     "query": "SELECT last(\"classes\") FROM \"coverage\" WHERE (\"owner\" =~ /^$folder$/ AND \"repo\" =~ /^$job$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "classes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    },
    {
     "alias": "Lines",
     "measurement": "coverage",
     "query": "SELECT last(\"lines\") FROM \"coverage\" WHERE (\"owner\" =~ /^$folder$/ AND \"repo\" =~ /^$job$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "lines" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    },
    {
     "alias": "Branches",
     "measurement": "coverage",
     "query": "SELECT last(\"conditionals\") FROM \"coverage\" WHERE (\"owner\" =~ /^$folder$/ AND \"repo\" =~ /^$job$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "conditionals" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "构建详情",
   "type": "table",
   "description": "构建信息",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "measurement": "job",
     "query": "SELECT \"project_name\", \"build_number\", \"build_time\",\"build_agent_name\", \"build_result\", \"build_desc\" FROM \"$bussiness\" WHERE (\"project_name\" =~ /^$job$/ )",
     "select": [
      [
       { "params": [ "time" ], "type": "field" }
      ],
      [
       { "params": [ "jobname" ], "type": "field" }
      ],
      [
       { "params": [ "trigger" ], "type": "field" }
      ],
      [
       { "params": [ "jobtime" ], "type": "field" }
      ],
      [
       { "params": [ "joburl" ], "type": "field" }
      ],
      [
       { "params": [ "passed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "构建持续时间",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "#$tag_build_number",
     "groupBy": [
      { "params": [ "buildnumber" ], "type": "tag" }
     ],
     "measurement": "job",
     "query": "SELECT \"build_time\" FROM \"$bussiness\" WHERE (\"project_name\" =~ /^$job$/ )  GROUP BY \"build_number\"  ORDER by \"time\" ",
     "select": [
      [
       { "params": [ "jobtime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  }
 ]
}